apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-subscriber
  labels:
    app: python-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-subscriber
  template:
    metadata:
      labels:
        app: python-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python-subscriber"
        dapr.io/app-port: "5000"
    spec:
      containers:
      - name: python-subscriber
        image: dapriosamples/pubsub-python-subscriber:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always