apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplyapp
  labels:
    app: multiply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiply
  template:
    metadata:
      labels:
        app: multiply
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "multiplyapp"
        dapr.io/port: "5000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: multiply
        image: dapriosamples/distributed-calculator-slow-python:0.8.0
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
